import React from "react";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./transition.css";

import ColorSelector from "@/components/ColorSelector";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { HoverProvider } from "@/lib/hover-context";
import HoverFooter from "@/registry/open-source/hover-footer";
import ResizeNavBar from "@/registry/open-source/resize-navbar";
import { GoogleAnalytics } from "@next/third-parties/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<NuqsAdapter>
					<HoverProvider>
						<ResizeNavBar />
						{children}
					</HoverProvider>
				</NuqsAdapter>

				<HoverFooter />
			</body>
			<GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_KEY} />
		</html>
	);
}
