import React from "react";

import type { Metadata } from "next";

import "./transition.css";

import { ThemeProvider } from "@/components/ui/theme-provider";
import { HoverProvider } from "@/lib/hover-context";
import HoverFooter from "@/registry/open-source/hover-footer";
import ResizeNavBar from "@/registry/open-source/resize-navbar";
import { GoogleAnalytics } from "@next/third-parties/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<NuqsAdapter>
					<HoverProvider>
						<ThemeProvider
							attribute="class"
							defaultTheme="system"
							disableTransitionOnChange
							enableSystem
						>
							<ResizeNavBar />
							{children}

							<HoverFooter />
						</ThemeProvider>
					</HoverProvider>
				</NuqsAdapter>
			</body>
			<GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_KEY} />
		</html>
	);
}
