import { Suspense } from "react";

import HomePage from "@/components/HomePage";
import { getComponentFilesWithDates } from "@/lib/fetch";

export const categories = {
	All: [
		"3d-card",
		"3d-nav-bar",
		"accordion-slices",
		"action-search-bar",
		"animated-accordion",
		"animated-hover-card",
		"animated-list",
		"ascii-converter",
		"attractor",
		"aurora-background",
		"award-carousel",
		"background-beams",
		"background-boxes",
		"background-gradient",
		"background",
		"ballpit",
		"bento",
		"blur-vignette",
		"book-testimonials",
		"bottom-blur",
		"btn08",
		"bubble-text",
		"business-footer",
		"canvas-reveal",
		"card-deck",
		"card-hover",
		"card-rotation",
		"card-stack",
		"card-swap",
		"cards",
		"carousel-circle",
		"carousel-stack",
		"checkbox-animated",
		"chroma-grid",
		"cielia-replication",
		"circle-accordion",
		"circle-text",
		"circuit-board",
		"circular-bars-loader",
		"code-block",
		"color-change-cards",
		"color-picker",
		"colorful-text",
		"compare",
		"container-scroll",
		"content-with-image",
		"css-box",
		"cubes",
		"cursor-carousel",
		"cursor-follow",
		"cursor-mask",
		"curved-navbar",
		"dark-veil",
		"dialog-stack",
		"diamond-gallery",
		"dither",
		"dual-ring-loader",
		"dynamic-island",
		"dynamic-theme",
		"editor",
		"elastic-line",
		"electric-border",
		"expanding-tabs",
		"falling-text",
		"fancy-input",
		"faq-section",
		"faulty-terminal",
		"feature",
		"film-reel",
		"fishy-button",
		"flip-card",
		"flipped-menu",
		"flipping-text",
		"floating-dock",
		"floating-nav",
		"flower-menu",
		"flowing-nav",
		"fluid-glass",
		"fluid-morph",
		"focus-cards",
		"fold-hover-button",
		"folder",
		"follow-cursor",
		"following-eyes",
		"following-headers",
		"following-pointer",
		"fractal-grid",
		"frequency",
		"fullscreen-image",
		"fuzzy-overlay",
		"fuzzy-text",
		"galaxy-button",
		"ghost-label",
		"gif-text",
		"glass-nav",
		"globe",
		"glowing-background",
		"glowing-effect",
		"gooey-tabs",
		"gradient-background",
		"gradient-checkbox",
		"gradient-testimonials",
		"gravity",
		"grid-content",
		"grid-distortion",
		"grid-to-flex",
		"half-filled-text",
		"hero-highlight",
		"hero-parallax",
		"horizontal-cta",
		"horizontal-scroll-gallery",
		"hover-border",
		"hover-card",
		"hover-cards",
		"hover-gallery",
		"hover-squares",
		"hover",
		"icons",
		"image-reveal",
		"image-ripple",
		"image-wheel",
		"image-zoom",
		"infinite-carousel",
		"infinite-menu",
		"infinite-moving-cards",
		"infinite-scrolling-logos-animation",
		"info-card",
		"inner-glow",
		"input-animated",
		"lamp",
		"lane-card",
		"lanyard",
		"layout-grid",
		"lens",
		"letter-hover",
		"letter3d-swap",
		"light-rays",
		"line-background",
		"linear-dialog",
		"link-preview",
		"list-rotator",
		"logo-loop",
		"logo-particles",
		"macbook",
		"magic-bento",
		"magnet-lines",
		"marquee-along-svg",
		"mask-effect",
		"masonry",
		"matrix-background",
		"media-between-text",
		"meteors",
		"mobile-nav-basic",
		"mobile-nav",
		"model-viewer",
		"mouse-image-trail",
		"movie-gallery",
		"nav-bar",
		"navbar2",
		"navbar3",
		"navigation",
		"nine-dot-loader",
		"number-ticker",
		"opposite-scroll-links",
		"opposite-scroll",
		"page-transitions",
		"parallax-carousel",
		"parallax-floating",
		"parallax-scroll",
		"peel-reveal",
		"pin",
		"ping-pong",
		"pipeline",
		"pixel-image",
		"pointer",
		"popular-price-card",
		"position-aware-button",
		"power-off-slide",
		"preloader",
		"price-card",
		"pricing-table",
		"progress-carousel",
		"progressive-blur",
		"project-showcase",
		"random-letter-swap-hover",
		"resize-navbar",
		"rich-popover",
		"rounded-scrollbar",
		"sandbox",
		"scaling-button",
		"screen-saver",
		"scroll-float",
		"scroll-horizontal-2",
		"scroll-horizontal",
		"scroll-island",
		"scroll-reveal-paragraph",
		"scroll-reveal",
		"scroll-velocity",
		"scrollable-card-stack",
		"searchbar",
		"select-modal",
		"services",
		"shape-blur",
		"share-button",
		"shuffle-hero",
		"sidebar",
		"sideivdeo",
		"simple-footer",
		"simple-grid",
		"skeleton",
		"slice-accordion",
		"slide-button",
		"sliding-numbers",
		"smokey-cursor",
		"smooth-cursor",
		"smooth-slider",
		"snowflakes",
		"social-links",
		"sparkles",
		"spinner",
		"spotlight",
		"spring-element",
		"spring-faq",
		"spring-modal",
		"stacked-carousel",
		"stacking-cards",
		"starfield-wrapper",
		"sticker-peel",
		"sticky-scroll-reveal",
		"stripe-accordion",
		"stripes-preloader",
		"swap-column-features",
		"table",
		"tabs-transition-panel",
		"tabs",
		"target-cursor",
		"terminal",
		"text-along-path",
		"text-animate",
		"text-cursor",
		"text-curve",
		"text-enhanced",
		"text-focus",
		"text-gradient",
		"text-highlighter",
		"text-hover",
		"text-morph",
		"text-parallax-content",
		"text-proximity",
		"text-reveal",
		"text-roll",
		"text-rotate",
		"text-split",
		"text-trail",
		"text-type",
		"text-underline",
		"theme-animations",
		"threads",
		"three-bounce-loader",
		"three-dot-loader",
		"tiles-background",
		"timeline",
		"tool-tip",
		"tour",
		"tracing-beam",
		"tunnel",
		"typewriter-testimonials",
		"underline-to-background",
		"vertical-cut-reveal",
		"video-button",
		"video-hero",
		"video-player",
		"video-player2",
		"video-viewer",
		"view-list",
		"wobble-card",
		"word-tornado",
		"zoom-blur-card",
	],

	Cards: [
		"3d-card",
		"animated-hover-card",
		"card-deck",
		"card-hover",
		"card-rotation",
		"card-stack",
		"card-swap",
		"cards",
		"flip-card",
		"hover-card",
		"hover-cards",
		"info-card",
		"lane-card",
		"popular-price-card",
		"price-card",
		"stacking-cards",
		"wobble-card",
		"zoom-blur-card",
		"focus-cards",
		"color-change-cards",
	],

	Buttons: [
		"btn08",
		"fishy-button",
		"fold-hover-button",
		"galaxy-button",
		"position-aware-button",
		"scaling-button",
		"share-button",
		"slide-button",
		"video-button",
		"hover-border",
		"horizontal-cta",
	],

	Text: [
		"bubble-text",
		"colorful-text",
		"falling-text",
		"fuzzy-text",
		"gif-text",
		"half-filled-text",
		"letter-hover",
		"text-along-path",
		"text-cursor",
		"text-curve",
		"text-enhanced",
		"text-focus",
		"text-gradient",
		"text-highlighter",
		"text-hover",
		"text-morph",
		"text-parallax-content",
		"text-proximity",
		"text-reveal",
		"text-roll",
		"text-rotate",
		"text-split",
		"text-trail",
		"text-type",
		"text-underline",
		"hero-highlight",
	],

	"Text Animations": [
		"text-along-path",
		"text-animate",
		"text-cursor",
		"text-morph",
		"text-reveal",
		"text-roll",
		"text-rotate",
		"text-split",
		"text-trail",
		"text-type",
		"random-letter-swap-hover",
		"letter3d-swap",
		"flipping-text",
	],

	Backgrounds: [
		"aurora-background",
		"background-beams",
		"background-boxes",
		"background-gradient",
		"background",
		"blur-vignette",
		"dark-veil",
		"glowing-background",
		"gradient-background",
		"line-background",
		"matrix-background",
		"tiles-background",
		"light-rays",
		"progressive-blur",
		"shape-blur",
	],

	Carousels: [
		"award-carousel",
		"carousel-circle",
		"carousel-stack",
		"infinite-carousel",
		"stacked-carousel",
		"progress-carousel",
		"parallax-carousel",
	],

	"Media Galleries": [
		"film-reel",
		"marquee-along-svg",
		"image-wheel",
		"movie-gallery",
		"infinite-moving-cards",
		"infinite-scrolling-logos-animation",
	],

	Navigation: [
		"3d-nav-bar",
		"nav-bar",
		"navbar2",
		"navbar3",
		"navigation",
		"mobile-nav-basic",
		"mobile-nav",
		"curved-navbar",
		"floating-nav",
		"flower-menu",
		"sidebar",
		"horizontal-scroll-gallery",
		"tabs",
		"flowing-nav",
	],

	Loaders: [
		"circular-bars-loader",
		"dual-ring-loader",
		"nine-dot-loader",
		"preloader",
		"spinner",
		"three-bounce-loader",
		"three-dot-loader",
		"stripes-preloader",
	],

	Accordions: [
		"accordion-slices",
		"animated-accordion",
		"circle-accordion",
		"faq-section",
		"slice-accordion",
		"spring-faq",
		"stripe-accordion",
	],

	Images: [
		"fullscreen-image",
		"image-reveal",
		"image-ripple",
		"image-wheel",
		"image-zoom",
		"media-between-text",
		"pixel-image",
	],

	"3D & Canvas": [
		"3d-card",
		"attractor",
		"canvas-reveal",
		"cubes",
		"globe",
		"model-viewer",
		"lens",
	],

	"Data & Tables": ["table", "list-rotator", "number-ticker", "view-list"],

	"Forms & Inputs": [
		"action-search-bar",
		"checkbox-animated",
		"fancy-input",
		"input-animated",
		"select-modal",
		"searchbar",
	],

	"Cursor & Pointer Effects": [
		"cursor-carousel",
		"cursor-follow",
		"cursor-mask",
		"follow-cursor",
		"following-eyes",
		"following-pointer",
		"pointer",
		"smooth-cursor",
		"target-cursor",
		"smokey-cursor",
	],

	"Special Effects & FX": [
		"animated-list",
		"aurora-background",
		"ballpit",
		"electric-border",
		"elastic-line",
		"floating-dock",
		"fuzzy-overlay",
		"glowing-effect",
		"inner-glow",
		"magnet-lines",
		"peel-reveal",
		"sparkles",
		"spring-element",
		"spotlight",
		"tracing-beam",
		"tunnel",
		"wobble-card",
	],

	Utilities: ["ascii-converter", "sandbox", "editor", "pipeline", "tool-tip"],

	Videos: ["video-player", "video-player2", "video-viewer", "video-hero"],

	Testimonials: [
		"book-testimonials",
		"gradient-testimonials",
		"typewriter-testimonials",
	],

	"Grids & Layouts": [
		"chroma-grid",
		"grid-to-flex",
		"masonry",
		"layout-grid",
		"fractal-grid",
	],
};

export default async function Page({}: {}) {
	const files = await getComponentFilesWithDates();

	return (
		<>
			<Suspense fallback={<span>Loading</span>}>
				{" "}
				<HomePage files={files} />
			</Suspense>
		</>
	);
}
