import React from "react";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ThemeProvider } from "@/components/ui/theme-provider";
import ResizeNavBar from "@/registry/open-source/resize-navbar";
import { GoogleAnalytics } from "@next/third-parties/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import ColorSelector from "@/components/ColorSelector";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ColorSelector>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
					>
					<ResizeNavBar />
					<NuqsAdapter>{children}</NuqsAdapter>
				</ThemeProvider>
					</ColorSelector>
			</body>
			<GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_KEY} />
		</html>
	);
}
